/* KALP RETRO-64 UI v2 — 3 reels × 8 shots = 24 shots. */
(function(){
'use strict';
const TOTAL_REELS=3,SHOTS_PER_REEL=8;
const stages=['ENTRY','THREAT INTRODUCTION','FIRST ENGAGEMENT','CAPABILITY ESCALATION','MAJOR ESCALATION','BREAKTHROUGH','GATE / OBJECTIVE','NEXT THREAT'];
const state={reels:Array.from({length:TOTAL_REELS},(_,i)=>({number:i+1,status:i===0?'CURRENT':'LOCKED',shots:Array.from({length:SHOTS_PER_REEL},(_,j)=>({number:j+1,title:stages[j],description:'Awaiting mission generation.'}))}))};
function mount(){
 if(document.querySelector('#retro64ProductionV2'))return;
 const old=document.getElementById('retroGame');
 const host=old?.closest('.view')||old?.parentElement||document.body;
 const el=document.createElement('div');el.id='retro64ProductionV2';host.prepend(el);
 [...host.children].forEach(n=>{if(n!==el)n.style.display='none';});
 const css=document.createElement('style');css.textContent=`#retro64ProductionV2{font-family:system-ui,sans-serif}.r64v2-shell{padding:18px;max-width:1600px;margin:auto}.r64v2-head{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:14px}.r64v2-eyebrow{color:#e9bb68;font-size:10px;font-weight:800;letter-spacing:1.4px}.r64v2-head h2{margin:4px 0;color:#f1cf87;font:24px Georgia}.r64v2-head p{margin:0;color:#8da1ad}.r64v2-total{min-width:105px;text-align:center;border:1px solid #e9bb68;border-radius:10px;padding:10px;background:#07131d}.r64v2-total b{display:block;color:#f6d38c;font-size:24px}.r64v2-total span{font-size:8px;color:#9eb0ba}.r64v2-arc{display:grid;grid-template-columns:repeat(8,1fr);gap:6px;margin-bottom:14px}.r64v2-stage{background:#07131d;border:1px solid #294555;border-radius:7px;padding:8px}.r64v2-stage i{display:block;color:#e9bb68;font-style:normal;font-size:9px}.r64v2-stage span{display:block;color:#aebfc8;font-size:8px;margin-top:4px;line-height:1.25}.r64v2-reels{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.r64v2-reel{background:#091722ee;border:1px solid #294555;border-radius:9px;padding:10px}.r64v2-reel.current{border-color:#66cce2}.r64v2-reel.generated{border-color:#4ed6a0}.r64v2-reel.locked{opacity:.65}.r64v2-reelhead{display:flex;justify-content:space-between;align-items:start;margin-bottom:8px}.r64v2-reelhead span{display:block;color:#e9bb68;font-size:9px;font-weight:800}.r64v2-reelhead strong{display:block;color:#f1cf87;font-size:16px;margin-top:3px}.r64v2-reelhead em{font-style:normal;color:#4ed6a0;font-size:8px}.r64v2-shots{display:grid;grid-template-columns:repeat(2,1fr);gap:5px}.r64v2-shot{background:#07131d;border:1px solid #203946;border-radius:6px;padding:7px;min-height:54px}.r64v2-shot b{color:#66cce2;font-size:9px;margin-right:5px}.r64v2-shot span{color:#e8eef2;font-size:9px}.r64v2-shot small{display:block;color:#78909c;font-size:8px;margin-top:4px;line-height:1.3}.r64v2-action{width:100%;margin-top:9px;padding:9px;border:0;border-radius:7px;background:linear-gradient(135deg,#f6d38c,#b87827);color:#07131a;font-weight:800;cursor:pointer}.r64v2-action:disabled{opacity:.4;cursor:not-allowed}.r64v2-footer{display:flex;justify-content:space-between;gap:10px;margin-top:10px;padding:10px;border:1px solid #294555;border-radius:8px;background:#07131d;color:#8da1ad;font-size:9px}.r64v2-footer b{color:#f1cf87}@media(max-width:1050px){.r64v2-arc{grid-template-columns:repeat(4,1fr)}.r64v2-reels{grid-template-columns:1fr}}@media(max-width:650px){.r64v2-arc{grid-template-columns:repeat(2,1fr)}}`;
 document.head.appendChild(css);
 render();
}
function render(){const el=document.querySelector('#retro64ProductionV2');if(!el)return;el.innerHTML=`<section class="r64v2-shell"><header class="r64v2-head"><div><div class="r64v2-eyebrow">RETRO-64 · MISSION PRODUCTION</div><h2>3-Reel Cinematic Mission</h2><p>Mission DNA → Reel 01 → Reel 02 → Reel 03</p></div><div class="r64v2-total"><b>24</b><span>TOTAL SHOTS</span></div></header><div class="r64v2-arc">${stages.map((s,i)=>`<div class="r64v2-stage"><i>${String(i+1).padStart(2,'0')}</i><span>${s}</span></div>`).join('')}</div><div class="r64v2-reels">${state.reels.map(r=>`<article class="r64v2-reel ${r.status.toLowerCase()}"><div class="r64v2-reelhead"><div><span>REEL ${String(r.number).padStart(2,'0')}</span><strong>8 SHOTS</strong></div><em>${r.status}</em></div><div class="r64v2-shots">${r.shots.map(s=>`<div class="r64v2-shot"><b>${String(s.number).padStart(2,'0')}</b><span>${s.title}</span><small>${s.description}</small></div>`).join('')}</div><button class="r64v2-action" data-reel="${r.number}" ${r.status==='LOCKED'?'disabled':''}>${r.status==='CURRENT'?'GENERATE REEL '+String(r.number).padStart(2,'0'):r.status==='GENERATED'?'REEL GENERATED':'RESUME REEL '+String(r.number).padStart(2,'0')}</button></article>`).join('')}</div><footer class="r64v2-footer"><span>8 progression stages = mission DNA</span><b>3 × 8 = 24 production shots</b><span>Continuity preserved across reels</span></footer></section>`;document.querySelectorAll('.r64v2-action').forEach(b=>b.onclick=()=>{const n=+b.dataset.reel;state.reels[n-1].status='GENERATED';if(n<TOTAL_REELS)state.reels[n].status='CURRENT';render();});}
function boot(){mount();}
window.KALP_RETRO64_UI_V2={boot,state,TOTAL_REELS,SHOTS_PER_REEL};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
