import test from "node:test";
import assert from "node:assert/strict";
import { ExperimentSyncEngine, InMemoryRemoteExperimentSyncAdapter, ManualConflictResolver } from "./sync-engine.js";
import { InMemoryOfflineQueue } from "../contracts/offline.js";
import { InMemoryExperimentRepository } from "../contracts/data.js";

test("sync accepts queued mutations and drains only after successful synchronization",async()=>{const q=new InMemoryOfflineQueue();q.enqueue({mutationId:"m1",experimentId:"e1",baseRevision:0,command:{type:"START"}});const engine=new ExperimentSyncEngine(q,new InMemoryExperimentRepository(),new InMemoryRemoteExperimentSyncAdapter());const report=await engine.sync("e1");assert.equal(report.state,"ONLINE");assert.equal(report.applied,1);assert.equal(q.pending("e1").length,0);});
test("sync detects remote revision ahead and preserves the mutation for resolution",async()=>{const q=new InMemoryOfflineQueue();q.enqueue({mutationId:"m1",experimentId:"e1",baseRevision:0,command:{type:"START"}});const remote=new InMemoryRemoteExperimentSyncAdapter();await remote.push({mutationId:"remote",experimentId:"e1",baseRevision:0,command:{type:"START"}});const engine=new ExperimentSyncEngine(q,new InMemoryExperimentRepository(),remote,new ManualConflictResolver());const report=await engine.sync("e1");assert.equal(report.state,"CONFLICT");assert.equal(report.conflicts[0].reason,"REMOTE_REVISION_AHEAD");assert.equal(q.pending("e1").length,1);});
test("duplicate remote mutation is reported without replaying it",async()=>{const q=new InMemoryOfflineQueue();const remote=new InMemoryRemoteExperimentSyncAdapter();const mutation={mutationId:"m1",experimentId:"e1",baseRevision:0,command:{type:"START" as const}};q.enqueue(mutation);q.enqueue({ ...mutation, mutationId:"m2" });await remote.push(mutation);const engine=new ExperimentSyncEngine(q,new InMemoryExperimentRepository(),remote);const report=await engine.sync("e1");assert.equal(report.state,"CONFLICT");assert.equal(report.duplicates,1);});
