import assert from "node:assert/strict";
import test from "node:test";
import { InMemoryExperimentRepository } from "../contracts/data.js";
import { InMemoryOfflineQueue } from "../contracts/offline.js";
import type { OfflineMutation } from "../contracts/offline.js";
import type { ExperimentSnapshot } from "../runtime/types.js";
import type { RemoteExperimentSyncAdapter, RemoteExperimentRecord, RemoteMutationResult } from "./remote-sync-contract.js";
import { KMRLRemoteHttpError, KMRLRemoteConflictError } from "./supabase-remote-adapter.js";
import { SyncHardeningEngine } from "./sync-hardening.js";

const snapshot=(revision:number):ExperimentSnapshot=>({experimentId:"exp-hardening",status:"RUNNING",tick:revision,revision,science:{} as ExperimentSnapshot["science"],checkpoints:[],measurements:[]});
const mutation=(baseRevision:number):OfflineMutation=>({mutationId:`m-${baseRevision}`,experimentId:"exp-hardening",command:{type:"PAUSE"},baseRevision});
class FakeRemote implements RemoteExperimentSyncAdapter{public remote:ExperimentSnapshot|undefined;public putFailures=0;public puts=0;async getExperiment():Promise<RemoteExperimentRecord|undefined>{return this.remote?{snapshot:structuredClone(this.remote),updatedAt:new Date().toISOString()}:undefined;}async putExperiment(_id:string,next:ExperimentSnapshot,expectedRevision:number):Promise<RemoteExperimentRecord>{this.puts+=1;if(this.putFailures>0){this.putFailures-=1;throw new KMRLRemoteHttpError(503,"temporary outage");}if(this.remote&&this.remote.revision!==expectedRevision)throw new KMRLRemoteConflictError(this.remote);this.remote={...structuredClone(next),revision:expectedRevision+1};return{snapshot:structuredClone(this.remote),updatedAt:new Date().toISOString()};}async applyMutation():Promise<RemoteMutationResult>{throw new Error("not used");}}

test("retries transient remote failures with exponential backoff and preserves queue until success",async()=>{const repository=new InMemoryExperimentRepository();const offline=new InMemoryOfflineQueue();const remote=new FakeRemote();repository.save(snapshot(1));offline.enqueue(mutation(0));remote.putFailures=2;const delays:number[]=[];const engine=new SyncHardeningEngine(repository,offline,remote,{maxAttempts:3,baseDelayMs:10,sleep:async ms=>{delays.push(ms);}});const report=await engine.sync("exp-hardening");assert.equal(report.state,"ONLINE");assert.equal(report.attempts,4);assert.deepEqual(delays,[10,20]);assert.equal(offline.pending("exp-hardening").length,0);assert.equal(remote.puts,3);});

test("transient exhaustion becomes OFFLINE and leaves durable mutations pending",async()=>{const repository=new InMemoryExperimentRepository();const offline=new InMemoryOfflineQueue();const remote=new FakeRemote();repository.save(snapshot(1));offline.enqueue(mutation(0));remote.putFailures=10;const engine=new SyncHardeningEngine(repository,offline,remote,{maxAttempts:3,baseDelayMs:5,sleep:async()=>{}});const report=await engine.sync("exp-hardening");assert.equal(report.state,"OFFLINE");assert.equal(report.attempts,3);assert.equal(offline.pending("exp-hardening").length,1);assert.equal(report.pendingMutations,1);});

test("revision conflict becomes CONFLICT without clearing the pending mutation",async()=>{const repository=new InMemoryExperimentRepository();const offline=new InMemoryOfflineQueue();const remote=new FakeRemote();repository.save(snapshot(1));offline.enqueue(mutation(0));remote.remote=snapshot(2);const engine=new SyncHardeningEngine(repository,offline,remote,{sleep:async()=>{}});const report=await engine.sync("exp-hardening");assert.equal(report.state,"CONFLICT");assert.equal(report.conflict?.remoteRevision,2);assert.equal(report.conflict?.local.mutationId,"m-0");assert.equal(offline.pending("exp-hardening").length,1);});

test("successful retry after an outage provides durable recovery",async()=>{const repository=new InMemoryExperimentRepository();const offline=new InMemoryOfflineQueue();const remote=new FakeRemote();repository.save(snapshot(1));offline.enqueue(mutation(0));remote.putFailures=3;const engine=new SyncHardeningEngine(repository,offline,remote,{maxAttempts:2,baseDelayMs:1,sleep:async()=>{}});const failed=await engine.sync("exp-hardening");assert.equal(failed.state,"OFFLINE");assert.equal(offline.pending("exp-hardening").length,1);const recovered=await engine.sync("exp-hardening");assert.equal(recovered.state,"ONLINE");assert.equal(offline.pending("exp-hardening").length,0);});
