class StemExperiment {
  final String id, domain, name, modelId, status;
  const StemExperiment(this.id, this.domain, this.name, this.modelId, this.status);
}

const approvedWorkbook = 'KALP_STEM_LAB_MASTER_CATALOG_v1_0_collision_approved.xlsx';
const approvedSha256 = 'd20c89ea77d8eaf8a5c59ea0fd91d169138a9f5de9d07e135b561aa9d79f54d8';

const experiments = <StemExperiment>[
  StemExperiment('PHY-MEC-001','PHYSICS','Constant Force Motion','constant_force','DEFINED'),
  StemExperiment('PHY-MEC-002','PHYSICS','Free Fall','free_fall','DEFINED'),
  StemExperiment('PHY-MEC-003','PHYSICS','Projectile Motion','projectile_motion','DEFINED'),
  StemExperiment('PHY-MEC-004','PHYSICS','Spring-Mass Oscillation','spring_mass','DEFINED'),
  StemExperiment('PHY-MEC-005','PHYSICS','Pendulum','pendulum','DEFINED'),
  StemExperiment('PHY-MEC-006','PHYSICS','Friction on an Incline','incline_friction','DEFINED'),
  StemExperiment('PHY-MEC-007','PHYSICS','Conservation of Momentum','collision_momentum','DEFINED'),
  StemExperiment('PHY-MEC-008','PHYSICS','Work and Energy','work_energy','DEFINED'),
  StemExperiment('PHY-MEC-009','PHYSICS','Power Measurement','power','DEFINED'),
  StemExperiment('PHY-MEC-010','PHYSICS','Circular Motion','circular_motion','DEFINED'),
  StemExperiment('PHY-THM-001','PHYSICS','Heating and Cooling','heat_transfer','DEFINED'),
  StemExperiment('PHY-THM-002','PHYSICS','Thermal Expansion','thermal_expansion','DEFINED'),
  StemExperiment('PHY-OPT-001','PHYSICS','Reflection from a Mirror','reflection','DEFINED'),
  StemExperiment('PHY-OPT-002','PHYSICS','Refraction through a Medium','refraction','DEFINED'),
  StemExperiment('PHY-ELC-001','PHYSICS',"Ohm's Law",'ohms_law','DEFINED'),
  StemExperiment('CHE-MIX-001','CHEMISTRY','Heating Water: Observe Temperature Change','heating_water','DEFINED'),
  StemExperiment('CHE-MIX-002','CHEMISTRY','Mixing Materials: Observe a System Change','registered_reaction','DEFINED'),
  StemExperiment('CHE-ACB-001','CHEMISTRY','Acid-Base Neutralization','acid_base_neutralization','DEFINED'),
  StemExperiment('CHE-ACB-002','CHEMISTRY','pH and Dilution','ph_dilution','DEFINED'),
  StemExperiment('CHE-STO-001','CHEMISTRY','Stoichiometry','stoichiometry','DEFINED'),
  StemExperiment('CHE-STO-002','CHEMISTRY','Limiting Reagent','limiting_reagent','DEFINED'),
  StemExperiment('CHE-ELC-001','CHEMISTRY','Simple Electrolysis','electrolysis','DEFINED'),
  StemExperiment('CHE-ELC-002','CHEMISTRY','Galvanic Cell','galvanic_cell','DEFINED'),
  StemExperiment('CHE-THM-001','CHEMISTRY','Exothermic Reaction','reaction_heat','DEFINED'),
  StemExperiment('CHE-THM-002','CHEMISTRY','Endothermic Reaction','reaction_heat','DEFINED'),
  StemExperiment('CHE-MAT-001','CHEMISTRY','Steel Making','steelmaking','DEFINED'),
  StemExperiment('CHE-MAT-002','CHEMISTRY','Alloy Composition','alloy_composition','DEFINED'),
  StemExperiment('CHE-KIN-001','CHEMISTRY','Reaction Rate vs Temperature','reaction_rate_temperature','DEFINED'),
  StemExperiment('CHE-KIN-002','CHEMISTRY','Concentration and Reaction Rate','reaction_rate_concentration','DEFINED'),
  StemExperiment('CHE-ORG-001','CHEMISTRY','Esterification Model','esterification','DEFINED'),
  StemExperiment('MAT-ALG-001','MATHEMATICS','Linear Equation Lab','linear_equation','DEFINED'),
  StemExperiment('MAT-ALG-002','MATHEMATICS','Quadratic Equation Lab','quadratic_equation','DEFINED'),
  StemExperiment('MAT-ALG-003','MATHEMATICS','Systems of Equations','linear_system','DEFINED'),
  StemExperiment('MAT-GEO-001','MATHEMATICS','Triangle Geometry','triangle_geometry','DEFINED'),
  StemExperiment('MAT-GEO-002','MATHEMATICS','Circle Geometry','circle_geometry','DEFINED'),
  StemExperiment('MAT-GEO-003','MATHEMATICS','Area and Volume','mensuration','DEFINED'),
  StemExperiment('MAT-TRG-001','MATHEMATICS','Sine and Cosine Lab','trigonometry','DEFINED'),
  StemExperiment('MAT-TRG-002','MATHEMATICS','Right Triangle Explorer','right_triangle','DEFINED'),
  StemExperiment('MAT-CAL-001','MATHEMATICS','Derivative Explorer','derivative','DEFINED'),
  StemExperiment('MAT-CAL-002','MATHEMATICS','Integral / Area Explorer','integral','DEFINED'),
  StemExperiment('MAT-STA-001','MATHEMATICS','Mean Median Mode Lab','descriptive_statistics','DEFINED'),
  StemExperiment('MAT-STA-002','MATHEMATICS','Standard Deviation Lab','standard_deviation','DEFINED'),
  StemExperiment('MAT-PRB-001','MATHEMATICS','Probability Simulator','probability','DEFINED'),
  StemExperiment('MAT-VEC-001','MATHEMATICS','Vector Addition','vector_addition','DEFINED'),
  StemExperiment('MAT-SEQ-001','MATHEMATICS','Sequences and Series','sequence_series','DEFINED'),
];
