export type RetroAudioIntensity="LOW"|"MEDIUM"|"HIGH"|"VERY_HIGH"|"PEAK"|"TENSION";
export interface RetroAudioDNA{
  identity:string; music_style:string; rhythmic_language:string; ambience:string;
  core_sfx:string[]; escalation:string[]; transition_cues:string[]; finale_cue:string;
  mix_direction:string; reference_fidelity:string;
}
export interface RetroSceneAudio{
  scene:number; music:string; rhythm:string; ambience:string; sfx:string[];
  intensity:RetroAudioIntensity; transition:string; mix:string;
}
const P:Record<string,RetroAudioDNA>={
"Contra":{identity:"Military arcade action",music_style:"Aggressive arcade action-rock with driving synth and percussion",rhythmic_language:"Fast 4/4 combat pulse with sharp action accents",ambience:"Rain, jungle insects, radio, engines and helicopter rotor",core_sfx:["Gunfire","Explosions","Shell casings","Helicopter rotor","Radio chatter"],escalation:["Heavier percussion","Armored-engine rumble","Increased aerial rotor presence"],transition_cues:["Threat stinger","Weapon-upgrade cue","Breakthrough impact","Gate-opening rise"],finale_cue:"Abrupt unresolved-threat sting",mix_direction:"Punchy impacts; music supports action without masking dialogue",reference_fidelity:"Arcade-era military sonic grammar; do not copy original recordings"},
"Mario":{identity:"Bright platform adventure",music_style:"Upbeat melodic platform-game motif with playful rhythmic bounce",rhythmic_language:"Bouncy syncopation with jump, coin and power-up accents",ambience:"Kingdom wind, water, underground reverb and castle tension",core_sfx:["Jump","Coin","Block hit","Enemy stomp","Pipe transition","Power-up"],escalation:["Denser percussion","Castle tension","Broader objective reveal"],transition_cues:["Level transition","Power-up flourish","Castle-entry sting","Objective cue"],finale_cue:"Brief victory resolution then next-world teaser",mix_direction:"Keep gameplay cues crisp and musically readable",reference_fidelity:"Platform-adventure sonic grammar; do not copy original recordings"},
"Road Fighter":{identity:"High-speed arcade racing",music_style:"Driving electronic racing pulse synchronized with engine propulsion",rhythmic_language:"Fast continuous pulse with acceleration layers",ambience:"Engine RPM, wind rush, road noise, traffic and tires",core_sfx:["Engine rev","Acceleration","Tire squeal","Traffic pass","Collision","Fuel warning"],escalation:["Rising engine intensity","Denser traffic","Stronger speed transitions"],transition_cues:["Fuel cue","Road transition","Final-sprint rise"],finale_cue:"High-speed finish sting with engine release",mix_direction:"Engine and tire dynamics form the primary rhythmic layer",reference_fidelity:"Arcade racing momentum; do not copy original recordings"},
"Kung Fu":{identity:"Compact martial-arts arcade combat",music_style:"Tense martial-arts pulse with sparse melody and impact-driven rhythm",rhythmic_language:"Short attack/recovery phrases synchronized to combat",ambience:"Temple room tone, footsteps and floor transitions",core_sfx:["Punch","Kick","Jump attack","Weapon throw","Enemy hit","Boss cue"],escalation:["Denser impacts","Stronger boss hits","Tighter upper-floor tempo"],transition_cues:["Floor transition","Boss arrival","Stairway rise"],finale_cue:"Heavy final impact then brief rescue resolution",mix_direction:"Impacts remain dry, immediate and spatially readable",reference_fidelity:"Martial-arts arcade combat grammar; do not copy original recordings"},
"Legend of Kage":{identity:"Fast vertical ninja action",music_style:"Japanese-inspired arcade action pulse with flute/percussion color",rhythmic_language:"Rapid attack pulses with airy climbing transitions",ambience:"Forest wind, leaves, birds, water and fortress air",core_sfx:["Sword slash","Shuriken","Enemy hit","Jump/land","Tree movement","Castle impact"],escalation:["Faster percussion","Stronger fortress impacts","Open mix for vertical reveals"],transition_cues:["Forest transition","Fortress reveal","Rescue cue"],finale_cue:"Rescue flourish with seasonal transition",mix_direction:"Balance weapon cues with spacious forest ambience",reference_fidelity:"Ninja arcade sonic grammar; do not copy original recordings"}
};
export function getRetroAudioDNA(game:string):RetroAudioDNA{
  return structuredClone(P[game]||{identity:"Retro arcade action",music_style:"Period-inspired arcade action",rhythmic_language:"Clear gameplay pulse",ambience:"Environment and movement",core_sfx:["Movement","Impact","Environment"],escalation:["Increase density at major escalation"],transition_cues:["Progression transition"],finale_cue:"Next-threat sting",mix_direction:"Prioritize gameplay clarity",reference_fidelity:"Genre-faithful reinterpretation; do not copy original recordings"});
}
export function buildRetroSceneAudio(game:string):RetroSceneAudio[]{
 const a=getRetroAudioDNA(game), i=[["LOW","Opening mission cue"],["MEDIUM","Threat stinger"],["HIGH","Combat engagement"],["MEDIUM","Capability cue"],["VERY_HIGH","Major escalation"],["PEAK","Breakthrough impact"],["TENSION","Objective threshold"],["PEAK",""+a.finale_cue]] as const;
 return i.map((x,n)=>({scene:n+1,music:a.music_style,rhythm:a.rhythmic_language,ambience:a.ambience,sfx:a.core_sfx,intensity:x[0] as RetroAudioIntensity,transition:x[1],mix:a.mix_direction}));
}
