type Obj = Record<string, unknown>;

const LABELS: Array<[string,string]> = [
  ["lagna","लग्न"],["moonSign","चंद्र राशि"],["sunSign","सूर्य राशि"],["nakshatra","नक्षत्र"],["nakshatraPada","नक्षत्र पाद"],["nakshatraLord","नक्षत्र स्वामी"],["tithi","तिथि"],["yoga","योग"],["karana","करण"],["mangalDosha","मंगल दोष"],["dasha","दशा"]
];
function obj(v: unknown): Obj { return v && typeof v === "object" && !Array.isArray(v) ? v as Obj : {}; }
function value(v: unknown): string { if (v === null || v === undefined || v === "") return "प्रदाता ने उपलब्ध नहीं कराया"; if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") return String(v); const r=obj(v); for (const k of ["value","name","label","sign","rashi","degreeText","degree"]) if (r[k] !== undefined) return value(r[k]); return "उपलब्ध"; }
function evidence(data: Obj, key: string): string { const e=obj(data.evidence); return typeof e[key] === "string" ? e[key] as string : (data[key] == null ? "UNAVAILABLE" : "PROVIDER"); }
function source(status: string): [string,string] { if (status === "CALCULATED") return ["KALP · Calculated","calculated"]; if (status === "PROVIDER") return ["OpenKundali · Provider","provider"]; if (status === "PARTIAL") return ["Partial Evidence","partial"]; return ["Unavailable","unavailable"]; }
function cleanName(v: unknown): string { const map: Record<string,string> = {Aquarius:"कुंभ",Scorpio:"वृश्चिक",Capricorn:"मकर",Mercury:"बुध",Rahu:"राहु",Sun:"सूर्य",Moon:"चंद्र",Mars:"मंगल",Jupiter:"गुरु",Venus:"शुक्र",Saturn:"शनि",Ketu:"केतु"}; const s=value(v); return map[s] ?? s; }
function dashaText(v: unknown): string { const d=obj(v); if (Object.keys(d).length === 0) return value(v); const parts=[]; if (d.mahadasha ?? d.name) parts.push(`महादशा: ${cleanName(d.mahadasha ?? d.name)}`); if (d.antardasha) parts.push(`अंतरदशा: ${cleanName(d.antardasha)}`); if (d.pratyantardasha) parts.push(`प्रत्यंतरदशा: ${cleanName(d.pratyantardasha)}`); return parts.length ? parts.join(" · ") : "प्रदाता ने उपलब्ध नहीं कराया"; }
function render(answer: HTMLElement): void {
  if (answer.querySelector(".kalp-canonical-renderer")) return;
  const json=answer.querySelector(".kundli-json"); if(!json) return;
  let payload:Obj; try{payload=JSON.parse(json.textContent??"{}") as Obj;}catch{return;}
  const data=obj(payload.data);
  const canonical=Object.keys(obj(data.canonical)).length ? obj(data.canonical) : data;
  const rows=LABELS.map(([key,label])=>{ const raw=canonical[key]; const status=evidence(canonical,key); const [badge,cls]=source(status); const display=key==="dasha"?dashaText(raw):cleanName(raw); return `<article class="kalp-canonical-card"><div><span class="kalp-canonical-label">${label}</span><strong>${escapeHtml(display)}</strong></div><span class="kalp-canonical-badge ${cls}"><i></i>${badge}</span></article>`; }).join("");
  const yoga=Array.isArray(canonical.yogaDetails)?canonical.yogaDetails:[];
  const planets=Array.isArray(canonical.planets)?canonical.planets:[];
  const section=document.createElement("section"); section.className="kalp-canonical-renderer";
  section.innerHTML=`<div class="kalp-canonical-heading"><div><span class="kalp-canonical-eyebrow">KALP-KUNDLI-CANONICAL-v1</span><h3>कुंडली का प्रमाणित सार</h3><p>यह दृश्य केवल canonical chart fields को render करता है। Legacy provider field mapping पर निर्भर नहीं है।</p></div><span class="kalp-canonical-status">${escapeHtml(String(payload.status??"UNKNOWN"))}</span></div><div class="kalp-canonical-grid">${rows}</div>${yoga.length?`<section class="kalp-canonical-sub"><h4>प्रदाता द्वारा दिए गए योग</h4><ul>${yoga.map((y)=>`<li>${escapeHtml(value(obj(y).name??y))}${obj(y).description?` — ${escapeHtml(value(obj(y).description))}`:""}</li>`).join("")}</ul></section>`:""}${planets.length?`<section class="kalp-canonical-sub"><h4>ग्रह स्थिति</h4><div class="kalp-canonical-planets">${planets.map((p)=>{const r=obj(p);return `<article><strong>${escapeHtml(cleanName(r.name??r.planet))}</strong><span>${escapeHtml(cleanName(r.sign??r.rashi??r.zodiac))}</span>${r.degree!==undefined?`<span>${escapeHtml(String(r.degree))}°</span>`:""}${r.retrograde?`<span>वक्री</span>`:""}${r.combust?`<span>अस्त</span>`:""}</article>`}).join("")}</div></section>`:""}`;
  const legacy=answer.querySelector(".kundli-section"); if(legacy) (legacy as HTMLElement).hidden=true;
  const rich=answer.querySelectorAll(".kundli-rich-section"); rich.forEach((node)=>{(node as HTMLElement).hidden=true;});
  const details=answer.querySelector("details"); if(details) answer.insertBefore(section,details); else answer.insertBefore(section,answer.firstChild);
}
function escapeHtml(v:string):string{return v.replace(/[&<>\"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]??c));}
function styles():void{if(document.getElementById("kalp-canonical-renderer-styles"))return;const s=document.createElement("style");s.id="kalp-canonical-renderer-styles";s.textContent=`.kalp-canonical-renderer{margin-top:16px;padding:16px;border:1px solid #cbd5e1;border-radius:14px;background:#fff}.kalp-canonical-heading{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.kalp-canonical-eyebrow{font-size:.7rem;font-weight:700;letter-spacing:.08em;color:#475569}.kalp-canonical-heading h3{margin:2px 0 4px}.kalp-canonical-heading p{margin:0;color:#64748b;font-size:.85rem}.kalp-canonical-status{font-size:.7rem;font-weight:700;padding:5px 8px;border-radius:999px;background:#f1f5f9;color:#475569}.kalp-canonical-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:14px}.kalp-canonical-card{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:10px;border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc}.kalp-canonical-card>div{display:grid;gap:2px;min-width:0}.kalp-canonical-label{font-size:.76rem;color:#64748b}.kalp-canonical-card strong{overflow-wrap:anywhere}.kalp-canonical-badge{display:inline-flex;align-items:center;gap:5px;font-size:.68rem;font-weight:700;white-space:nowrap}.kalp-canonical-badge i{width:8px;height:8px;border-radius:50%;display:inline-block;background:#94a3b8}.kalp-canonical-badge.provider{color:#1d4ed8}.kalp-canonical-badge.provider i{background:#2563eb}.kalp-canonical-badge.calculated{color:#6d28d9}.kalp-canonical-badge.calculated i{background:#7c3aed}.kalp-canonical-badge.partial{color:#b45309}.kalp-canonical-badge.partial i{background:#d97706}.kalp-canonical-badge.unavailable{color:#64748b}.kalp-canonical-sub{margin-top:16px;padding-top:12px;border-top:1px solid #e2e8f0}.kalp-canonical-sub h4{margin:0 0 8px;color:#312e81}.kalp-canonical-sub ul{margin:0;padding-left:20px}.kalp-canonical-planets{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.kalp-canonical-planets article{display:grid;gap:2px;padding:9px;border:1px solid #e2e8f0;border-radius:9px;background:#f8fafc}.kalp-canonical-planets span{font-size:.78rem;color:#64748b}@media(max-width:700px){.kalp-canonical-grid{grid-template-columns:1fr}.kalp-canonical-planets{grid-template-columns:repeat(2,minmax(0,1fr))}}`;document.head.appendChild(s);}
styles();const answer=document.getElementById("answer");if(answer){const observer=new MutationObserver(()=>render(answer));observer.observe(answer,{childList:true,subtree:true});render(answer);}
