name: KMRL Sandbox Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - feature/kmral-sandbox-enduser-ui-v0.1

jobs:
  build_android:
    name: Build KMRL Sandbox APK
    type: build
    params:
      platform: android
      profile: preview
