export type ProviderRole = "market-data" | "news-intelligence" | "ai-intelligence" | "fixture";
export interface ProviderRequest { symbol?: string; query?: string; }
export interface NormalizedProviderResult { provider_id:string; provider_name:string; role:ProviderRole; status:"ok"|"rate_limited"|"unauthorized"|"error"|"not_configured"; observed_at:string; data:Record<string,unknown>; request_meta:{endpoint:string;adapter_version:string}; error?:string; }
export interface ProviderAdapter { readonly provider_id:string; readonly provider_name:string; readonly role:ProviderRole; fetch(request:ProviderRequest):Promise<NormalizedProviderResult>; }
const V="MM-PAF-v0.1";
async function call(endpoint:string, init?:RequestInit){const r=await fetch(endpoint,init);let data:Record<string,unknown>={};try{data=await r.json() as Record<string,unknown>}catch{}return {status:r.status,data,retryAfter:r.headers.get("retry-after")};}
async function callWith429Backoff(endpoint:string, init?:RequestInit, maxAttempts=3){for(let attempt=1;attempt<=maxAttempts;attempt++){const r=await call(endpoint,init);if(r.status!==429||attempt===maxAttempts)return r;const retrySeconds=Number(r.retryAfter);const delayMs=Number.isFinite(retrySeconds)&&retrySeconds>0?Math.min(retrySeconds*1000,5000):Math.min(1000*attempt,5000);await new Promise(resolve=>setTimeout(resolve,delayMs));}throw new Error("unreachable");}
async function callGemini503Backoff(endpoint:string, init?:RequestInit, maxAttempts=3){for(let attempt=1;attempt<=maxAttempts;attempt++){const r=await call(endpoint,init);if(r.status!==503||attempt===maxAttempts)return r;const retrySeconds=Number(r.retryAfter);const baseDelayMs=Number.isFinite(retrySeconds)&&retrySeconds>0?Math.min(retrySeconds*1000,5000):Math.min(1000*Math.pow(2,attempt-1),5000);const jitterMs=Math.floor(Math.random()*250);await new Promise(resolve=>setTimeout(resolve,baseDelayMs+jitterMs));}throw new Error("unreachable");}
/** Return only a credential-free endpoint for provenance/evidence metadata. Never expose provider credentials. */
export function safeEndpointForEvidence(endpoint:string):string{try{const u=new URL(endpoint);for(const p of ["apikey","api_key","key","token","access_token","authorization"]){u.searchParams.delete(p)}u.search="";return u.toString()}catch{return endpoint.replace(/([?&](?:apikey|api_key|key|token|access_token|authorization)=)[^&]*/gi,"$1<REDACTED>").replace(/\?$/g,"")}}
function norm(id:string,name:string,role:ProviderRole,endpoint:string,http:number,data:Record<string,unknown>,error?:string):NormalizedProviderResult{return{provider_id:id,provider_name:name,role,status:http===429?"rate_limited":http===401||http===403?"unauthorized":http>=200&&http<300?"ok":"error",observed_at:new Date().toISOString(),data,request_meta:{endpoint:safeEndpointForEvidence(endpoint),adapter_version:V},...(error?{error}:{})};}
export class AlphaVantageAdapter implements ProviderAdapter {readonly provider_id="MM-PROV-ALPHA-001";readonly provider_name="Alpha Vantage";readonly role="market-data" as const;async fetch(q:ProviderRequest):Promise<NormalizedProviderResult>{const k=process.env.ALPHA_VANTAGE_API_KEY;if(!k)return{provider_id:this.provider_id,provider_name:this.provider_name,role:this.role,status:"not_configured",observed_at:new Date().toISOString(),data:{},request_meta:{endpoint:"alphavantage",adapter_version:V},error:"ALPHA_VANTAGE_API_KEY missing"};const e=`https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=${encodeURIComponent(q.symbol??"IBM")}&apikey=${encodeURIComponent(k)}`;try{const r=await call(e);return norm(this.provider_id,this.provider_name,this.role,e,r.status,r.data)}catch(x){return norm(this.provider_id,this.provider_name,this.role,e,500,{},String(x))}}}
export class FinnhubAdapter implements ProviderAdapter {readonly provider_id="MM-PROV-FINNHUB-001";readonly provider_name="Finnhub";readonly role="market-data" as const;async fetch(q:ProviderRequest):Promise<NormalizedProviderResult>{const k=process.env.FINNHUB_API_KEY;if(!k)return{provider_id:this.provider_id,provider_name:this.provider_name,role:this.role,status:"not_configured",observed_at:new Date().toISOString(),data:{},request_meta:{endpoint:"finnhub",adapter_version:V},error:"FINNHUB_API_KEY missing"};const e=`https://finnhub.io/api/v1/quote?symbol=${encodeURIComponent(q.symbol??"AAPL")}&token=${encodeURIComponent(k)}`;try{const r=await call(e);return norm(this.provider_id,this.provider_name,this.role,e,r.status,r.data)}catch(x){return norm(this.provider_id,this.provider_name,this.role,e,500,{},String(x))}}}
export class GdeltAdapter implements ProviderAdapter {readonly provider_id="MM-PROV-GDELT-001";readonly provider_name="GDELT";readonly role="news-intelligence" as const;async fetch(q:ProviderRequest):Promise<NormalizedProviderResult>{const e=`https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(q.query??"India market demand")}&mode=artlist&format=json&maxrecords=10&sort=datedesc&timespan=1d`;try{const r=await callWith429Backoff(e,undefined,3);return norm(this.provider_id,this.provider_name,this.role,e,r.status,r.data,r.status===429?"GDELT rate limit persisted after bounded backoff":"")}catch(x){return norm(this.provider_id,this.provider_name,this.role,e,500,{},String(x))}}}
export class GeminiFreeTierAdapter implements ProviderAdapter {readonly provider_id="MM-PROV-GEMINI-001";readonly provider_name="Google Gemini Free Tier";readonly role="ai-intelligence" as const;async fetch(q:ProviderRequest):Promise<NormalizedProviderResult>{const k=process.env.GEMINI_API_KEY;if(!k)return{provider_id:this.provider_id,provider_name:this.provider_name,role:this.role,status:"not_configured",observed_at:new Date().toISOString(),data:{},request_meta:{endpoint:"gemini",adapter_version:V},error:"GEMINI_API_KEY missing"};const m=process.env.GEMINI_MODEL??"gemini-3.7-flash";const e=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(m)}:generateContent?key=${encodeURIComponent(k)}`;try{const r=await callGemini503Backoff(e,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:q.query??"Summarize public market signals without inventing facts."}]}]})},3);return norm(this.provider_id,this.provider_name,this.role,e,r.status,r.data,r.status===503?"Gemini 503 persisted after bounded backoff":"")}catch(x){return norm(this.provider_id,this.provider_name,this.role,e,500,{},String(x))}}}
export class SyntheticFixtureAdapter implements ProviderAdapter {readonly provider_id="MM-PAF-FIXTURE";readonly provider_name="Synthetic MM Provider Fixture";readonly role="fixture" as const;async fetch(_request:ProviderRequest):Promise<NormalizedProviderResult>{return{provider_id:this.provider_id,provider_name:this.provider_name,role:this.role,status:"ok",observed_at:new Date().toISOString(),data:{signal_id:"MM-SIG-001",confidence:.89},request_meta:{endpoint:"fixture",adapter_version:V}}}}
export const initialFreeProviderMesh:ProviderAdapter[]=[new AlphaVantageAdapter(),new FinnhubAdapter(),new GdeltAdapter(),new GeminiFreeTierAdapter()];
